name: Deploy to Vultr

on:
  push:
    branches:
      - main
      - develop  # Include any other branches you want to auto-deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build

      - name: Add SSH key to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 65.20.70.107 >> ~/.ssh/known_hosts

      - name: Deploy to server
        run: |
          scp -r ./dist/* root@65.20.70.107:/vehicle-maintenance-predictor/dist
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
