name: Deploy to Vultr

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key for deployment
        env:
          VULTR_PRIVATE_KEY: ${{ secrets.VULTR_PRIVATE_KEY }}
        run: |
          echo "$VULTR_PRIVATE_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H 65.20.85.5 >> ~/.ssh/known_hosts  # Replace with your Vultr server IP

      - name: Deploy to Vultr
        run: |
          # Replace with the actual deployment commands, e.g., upload your build
          scp -r dist/* root@65.20.85.5:/var/www/html  # Replace with your Vultr server IP and directory
